version: "3.7"
services:
  db:
    image: redis:alpine
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=wachtwoord
  scylla:
    image: scylladb/scylla
    ports:
      - "9042:9042"
